language: rust
os:
  - linux
  - windows
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - |
    if [ "$TRAVIS_RUST_VERSION" = nightly]; then
      rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
    else
      rustup component add clippy
    fi
script:
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      export LIBCLANG_PATH="C:\\Program Files\\LLVM\\\\bin"
      export TARGET="x86_64-pc-windows-msvc"
    else
      export TARGET="x86_64-unknown-linux-gnu"
    fi
  - rustup target add "$TARGET"
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose --target "$TARGET" --all
  - cargo test --verbose --target "$TARGET" --all
  - cargo package --verbose --target "$TARGET"
deploy:
  skip_cleanup: true
  provider: cargo
  token:
    secure: YtAG4bqk9BdKbt1ANGC1v6cK4fMmOXWfAFkPTDd68hhH7/FwIOPJ0kEc68ra6rBP230Q/TT2+ikBM30MzeNiChEmtHY/mt6GQQDj/SD47P4BurV+ooO0lFdE7282qFJVuQDzJ4STxGKh+XEVZwEZZifAYZ4578U7eq3qHYTYEzKJFlmNZs1NHGKssS5njc+AlPQnPZ7x+J5L/8jKsBP1NKiwATGoOFW1Q6g5jcml9se1ByL5SaSvtm2eQ04Zwg84+g2L5ETPWGdXn8ZUecTC8mDuL+G1RFUEISgJxKcBoqk8O6DpTfKTjRCzFoLJk7IKb4CEnq2rZska9tsEn+Am/PnDw2RAPCmfOldawx7tRmjsTNZ16aEIIxv8JJh02KNSVPO3TPqcMcZizIjxYxjCcLXBqcrEBVO2bV39D76lwb0b030cENvl0F2fQZWcEpRxaFNYP+HugxpE6D+R6CCM9lKEMFLvlcrGjCylr0id28KaQkd7y3jkRLEK4oRw6BHHPkQUhGubyHit1xtDwaFwCEirebxRBgNwbXrC2YCyjJZt30/t2prPa6krERDAiC/MiCwk62/UK8tg8JRBzRRv/AQTOEhZWFsY57B3RjDvM3q5L4RvCkgv5/rCod7LsAahhp+H/HSmRQNWJ0VbKLsHZjNXhh/g2Xe/M84vVaJn7bg=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux
